apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    run: mypod
spec:
  containers:
    - image: adityan28/myapp:v1
      name: nodewebapp
      imagePullPolicy: Never
      ports:
        - containerPort: 3001
  dnsPolicy: ClusterFirst
  restartPolicy: Always
